library(raster)
library(mopa)
x <- read.csv("data_name.csv")

r3 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/scaled/03.tif")
r4 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/scaled/04.tif")
r5 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/scaled/05.tif")
r12 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/scaled/012.tif")
r13 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/scaled/013.tif")
r14 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/scaled/014.tif")
r330 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/scaled/330.tif")
r420 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/scaled/420.tif")
r520 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/scaled/520.tif")
r720 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/scaled/720.tif")
rglob_20 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_20.tif")
rglob_30 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_30.tif")
rglob_50 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_50.tif")
rglob_70 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_70.tif")
rglob_90 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_90.tif")
rglob_100 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_100.tif")
rglob_110 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_110.tif")
rglob_120 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_120.tif")
rglob_140 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_140.tif")
rglob_150 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_150.tif")
rglob_190 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_190.tif")
rglob_200 <- raster("F:/github/bird/code/sdmdl/data/gis/layers/non-scaled/glob_200.tif")

testRaster <- raster::addLayer(r3,r4,r5,r12,r13,r14,r330,r420,r520,r720,rglob_20,rglob_30,rglob_50,rglob_70,rglob_90,rglob_100,rglob_110,rglob_120,rglob_140,rglob_150,rglob_190,rglob_200)

bg1 <- backgroundGrid(raster = testRaster)

bg.profiled <- OCSVMprofiling(xy = x, varstack = testRaster, background = bg1$xy)
RGEB  <- pseudoAbsences(xy = x, background = bg.profiled$absence, exclusion.buffer = 0.0000083, prevalence = -3.5)
RGEP  <- pseudoAbsences(xy = x, background = bg.profiled$absence, exclusion.buffer = 0.083, prevalence = -3.5)

write.csv(RGEB[["species1"]][["PA01"]][[1]],file='F:/github/bird/데이터생성/rs/저어새/Platalea_minor_total_1.csv')
write.csv(RGEP[["species1"]][["PA01"]][[1]],file='F:/github/bird/데이터생성/rs/저어새/Platalea_minor_total_2.csv')
